development:
  adapter: postgresql
  encoding: utf8
  database: rails4_development  
  pool: 5
  username: divya
  password:


test: &TEST
  adapter: postgresql
  encoding: utf8
  database: rails4_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: d1hlmvgk6ffo7h
  host: ec2-54-243-201-116.compute-1.amazonaws.com
  pool: 5
  username: sdxbdjglhqsapn 
  password: ZuXoBjHipJkTPszJ2l3x0Psf5w
  port: 5432

